proTwo/appTwo/urls.py
from django.urls import path
from appTwo import views

app_name = 'appTwo'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
]

proTwo/proTwo/urls.py
from django.contrib import admin
from django.urls import path, include
from appTwo import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('appTwo/',include('appTwo.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
]

proTwo/appTwo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    # additional
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

proTwo/appTwo/forms.py
from django import forms
from django.contrib.auth.models import User
from appTwo.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

proTwo/appTwo/views.py
from django.shortcuts import render
from appTwo.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# create your views here




def index(request):
    return render(request,'appTwo/index.html')


@login_required
def special(request):
    return render(request,'appTwo/special.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))



def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'appTwo/registration.html',
                  {'user_form':user_form,
                   'profile_form':profile_form,
                   'registered':registered})

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)


        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('special'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request,'appTwo/login.html',{})

proTwo/templates/appTwo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
</head>
<body>
    <div class="Container">
        <nav class="navbar navbar-default navbar static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'index' %}">HOME</a></li>
                    <li><a class="navbar-link" href="{% url 'appTwo:register' %}">REGISTER</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a></li>

                    {% if user.is_authenticated %}
                    <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                    <li><a class="navbar-link" href="{% url 'appTwo:user_login' %}">Login</a></li>
                    {% endif %}



                </ul>
            </div>
        </nav>
        <div class="container">
            {% block body_block%}
            <!-- Anything outside of this will be inherited if you extend -->
             {% endblock %}
        </div>
</body>
</html>

proTwo/templates/appTwo/index.html
{% extends "appTwo/base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>Django level Five</h1>
</div>

{% endblock %}

proTwo/templates/appTwo/login.html
{% extends 'appTwo/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'appTwo:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">
    </form>
</div>
{% endblock %}

proTwo/templates/appTwo/registration.html
{% extends "appTwo/base.html" %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
    {% if registered %}
    <h1>Thank you for registering!</h1>
    {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" value="Register">
    </form>
    {% endif %}
</div>
{% endblock %}

proTwo/templates/appTwo/special.html
{% extends 'appTwo/base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>You are logged in,nice!</h1>
</div>
{% endblock %}